#!/usr/bin/env php
<?php
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
}

$monitor = new \ServiceMonitor\Twitter\UserStreamMonitor(
    getenv('TWITTER_ACCESS_TOKEN'),
    getenv('TWITTER_ACCESS_TOKEN_SECRET'),
    getenv('TWITTER_CONSUMER_KEY'),
    getenv('TWITTER_CONSUMER_SECRET')
);
$monitor->setEvent(new \ServiceMonitor\Twitter\SampleEvent());
echo 'Start monitoring.' . PHP_EOL;
$monitor->start();
